name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1']
        gemfile: ['activerecord_5.2', 'activerecord_6.0', 'activerecord_6.1', 'activerecord_7.0']
        exclude:
          - ruby: '2.6'
            gemfile: 'activerecord_7.0'
          - ruby: '3.0'
            gemfile: 'activerecord_5.2'
          - ruby: '3.1'
            gemfile: 'activerecord_5.2'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
